"""baseline

Revision ID: df52986ca7d0
Revises: 
Create Date: 2026-06-25 20:39:54.407903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df52986ca7d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_bot_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_token_enc', sa.Text(), nullable=True),
    sa.Column('bot_username', sa.String(), nullable=True),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('public_base_url', sa.String(), nullable=True),
    sa.Column('webhook_set_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('trigger_mode', sa.String(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('deliver', sa.JSON(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('fired_count', sa.Integer(), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_id'), 'alarms', ['id'], unique=False)
    op.create_index('ix_alarms_market_status', 'alarms', ['market', 'status'], unique=False)
    op.create_index(op.f('ix_alarms_user_id'), 'alarms', ['user_id'], unique=False)
    op.create_index('ix_alarms_user_status', 'alarms', ['user_id', 'status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_index('ix_alerts_user_seen', 'alerts', ['user_id', 'seen'], unique=False)
    op.create_table('exchange_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.Enum('BYBIT', 'HYPERLIQUID', 'LIGHTER', name='venue'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('encrypted_credentials', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sync_cursor', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_error', sa.String(), nullable=True),
    sa.Column('sync_progress', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_accounts_id'), 'exchange_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_exchange_accounts_user_id'), 'exchange_accounts', ['user_id'], unique=False)
    op.create_table('perps_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_key', sa.String(), nullable=False),
    sa.Column('setup_name', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('emotion_before', sa.String(), nullable=True),
    sa.Column('emotion_after', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('mistakes', sa.Text(), nullable=True),
    sa.Column('lessons', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('mistake_tags', sa.JSON(), nullable=True),
    sa.Column('followed_plan', sa.Boolean(), nullable=True),
    sa.Column('was_overtrading', sa.Boolean(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('stop_triggered', sa.Boolean(), nullable=True),
    sa.Column('targets', sa.JSON(), nullable=True),
    sa.Column('screenshot_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'position_key', name='uq_perps_journal_user_poskey')
    )
    op.create_index(op.f('ix_perps_journal_id'), 'perps_journal', ['id'], unique=False)
    op.create_index(op.f('ix_perps_journal_position_key'), 'perps_journal', ['position_key'], unique=False)
    op.create_index(op.f('ix_perps_journal_user_id'), 'perps_journal', ['user_id'], unique=False)
    op.create_table('perps_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perps_tags_id'), 'perps_tags', ['id'], unique=False)
    op.create_index(op.f('ix_perps_tags_user_id'), 'perps_tags', ['user_id'], unique=False)
    op.create_table('playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('context_requirements', sa.Text(), nullable=True),
    sa.Column('entry_triggers', sa.Text(), nullable=True),
    sa.Column('invalidation', sa.Text(), nullable=True),
    sa.Column('management', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_playbook_user_name')
    )
    op.create_index(op.f('ix_playbooks_id'), 'playbooks', ['id'], unique=False)
    op.create_index(op.f('ix_playbooks_user_id'), 'playbooks', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('workspace', sa.String(), server_default='prop', nullable=False),
    sa.Column('what_worked', sa.Text(), nullable=True),
    sa.Column('what_didnt', sa.Text(), nullable=True),
    sa.Column('next_focus', sa.Text(), nullable=True),
    sa.Column('probe_flags', sa.JSON(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_type', 'period_start', 'workspace', name='uq_review_user_period_ws')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('telegram_link_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_link_codes_code'), 'telegram_link_codes', ['code'], unique=True)
    op.create_index(op.f('ix_telegram_link_codes_id'), 'telegram_link_codes', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_link_codes_user_id'), 'telegram_link_codes', ['user_id'], unique=False)
    op.create_table('telegram_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('bot_token_enc', sa.Text(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_telegram_link_user')
    )
    op.create_index(op.f('ix_telegram_links_id'), 'telegram_links', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_links_user_id'), 'telegram_links', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('levels', sa.JSON(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_watchlist_user_symbol')
    )
    op.create_index(op.f('ix_watchlist_items_id'), 'watchlist_items', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    op.create_table('balance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange_account_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_account_id', 'ts', 'kind', name='uq_balance_snapshot')
    )
    op.create_index(op.f('ix_balance_snapshots_exchange_account_id'), 'balance_snapshots', ['exchange_account_id'], unique=False)
    op.create_index(op.f('ix_balance_snapshots_id'), 'balance_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_balance_snapshots_user_id'), 'balance_snapshots', ['user_id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange_account_id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.Enum('BYBIT', 'HYPERLIQUID', 'LIGHTER', name='venue'), nullable=False),
    sa.Column('external_fill_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_class', sa.Enum('PERP', 'SPOT', name='assetclass'), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='side'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('fee_currency', sa.String(), nullable=True),
    sa.Column('funding_amount', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('risk_amount', sa.Float(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_exchange_account_id'), 'fills', ['exchange_account_id'], unique=False)
    op.create_index(op.f('ix_fills_external_fill_id'), 'fills', ['external_fill_id'], unique=False)
    op.create_index(op.f('ix_fills_id'), 'fills', ['id'], unique=False)
    op.create_index(op.f('ix_fills_symbol'), 'fills', ['symbol'], unique=False)
    op.create_index(op.f('ix_fills_user_id'), 'fills', ['user_id'], unique=False)
    op.create_table('perps_position_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_key', sa.String(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['perps_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perps_position_tags_id'), 'perps_position_tags', ['id'], unique=False)
    op.create_index(op.f('ix_perps_position_tags_position_key'), 'perps_position_tags', ['position_key'], unique=False)
    op.create_index(op.f('ix_perps_position_tags_user_id'), 'perps_position_tags', ['user_id'], unique=False)
    op.create_table('plan_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session_start_hour', sa.Integer(), nullable=False),
    sa.Column('regime_snapshot', sa.JSON(), nullable=True),
    sa.Column('playbook_id', sa.Integer(), nullable=True),
    sa.Column('a_setup_note', sa.Text(), nullable=True),
    sa.Column('shortlist', sa.JSON(), nullable=True),
    sa.Column('not_today', sa.Text(), nullable=True),
    sa.Column('mental_state', sa.String(), nullable=True),
    sa.Column('max_trades', sa.Integer(), nullable=True),
    sa.Column('max_daily_loss', sa.Float(), nullable=True),
    sa.Column('r_per_trade', sa.Float(), nullable=True),
    sa.Column('circuit_rules', sa.Text(), nullable=True),
    sa.Column('key_lesson', sa.Text(), nullable=True),
    sa.Column('tomorrow_focus', sa.Text(), nullable=True),
    sa.Column('htf_bias', sa.String(), nullable=True),
    sa.Column('ltf_bias', sa.String(), nullable=True),
    sa.Column('expectations', sa.Text(), nullable=True),
    sa.Column('key_levels_buy', sa.Text(), nullable=True),
    sa.Column('key_levels_sell', sa.Text(), nullable=True),
    sa.Column('did_well', sa.Text(), nullable=True),
    sa.Column('did_poorly', sa.Text(), nullable=True),
    sa.Column('eod_why', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_plan_card_user_date')
    )
    op.create_index(op.f('ix_plan_cards_id'), 'plan_cards', ['id'], unique=False)
    op.create_index(op.f('ix_plan_cards_user_id'), 'plan_cards', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange_account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_class', sa.Enum('PERP', 'SPOT', name='assetclass'), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='direction'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='positionstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('avg_entry', sa.Float(), nullable=False),
    sa.Column('avg_exit', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('total_fees', sa.Float(), nullable=False),
    sa.Column('total_funding', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('position_key', sa.String(), nullable=True),
    sa.Column('opened_at_source', sa.Enum('EXACT', 'ESTIMATED', name='openedatsource'), server_default='ESTIMATED', nullable=False),
    sa.Column('mfe_price', sa.Float(), nullable=True),
    sa.Column('mae_price', sa.Float(), nullable=True),
    sa.Column('mfe_usd', sa.Float(), nullable=True),
    sa.Column('mae_usd', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_exchange_account_id'), 'positions', ['exchange_account_id'], unique=False)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_position_key'), 'positions', ['position_key'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('position_fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['fills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'fill_id', name='uq_position_fill')
    )
    op.create_index(op.f('ix_position_fills_fill_id'), 'position_fills', ['fill_id'], unique=False)
    op.create_index(op.f('ix_position_fills_id'), 'position_fills', ['id'], unique=False)
    op.create_index(op.f('ix_position_fills_position_id'), 'position_fills', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_fills_position_id'), table_name='position_fills')
    op.drop_index(op.f('ix_position_fills_id'), table_name='position_fills')
    op.drop_index(op.f('ix_position_fills_fill_id'), table_name='position_fills')
    op.drop_table('position_fills')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_position_key'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_exchange_account_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_plan_cards_user_id'), table_name='plan_cards')
    op.drop_index(op.f('ix_plan_cards_id'), table_name='plan_cards')
    op.drop_table('plan_cards')
    op.drop_index(op.f('ix_perps_position_tags_user_id'), table_name='perps_position_tags')
    op.drop_index(op.f('ix_perps_position_tags_position_key'), table_name='perps_position_tags')
    op.drop_index(op.f('ix_perps_position_tags_id'), table_name='perps_position_tags')
    op.drop_table('perps_position_tags')
    op.drop_index(op.f('ix_fills_user_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_symbol'), table_name='fills')
    op.drop_index(op.f('ix_fills_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_external_fill_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_exchange_account_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_balance_snapshots_user_id'), table_name='balance_snapshots')
    op.drop_index(op.f('ix_balance_snapshots_id'), table_name='balance_snapshots')
    op.drop_index(op.f('ix_balance_snapshots_exchange_account_id'), table_name='balance_snapshots')
    op.drop_table('balance_snapshots')
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_telegram_links_user_id'), table_name='telegram_links')
    op.drop_index(op.f('ix_telegram_links_id'), table_name='telegram_links')
    op.drop_table('telegram_links')
    op.drop_index(op.f('ix_telegram_link_codes_user_id'), table_name='telegram_link_codes')
    op.drop_index(op.f('ix_telegram_link_codes_id'), table_name='telegram_link_codes')
    op.drop_index(op.f('ix_telegram_link_codes_code'), table_name='telegram_link_codes')
    op.drop_table('telegram_link_codes')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_playbooks_user_id'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_id'), table_name='playbooks')
    op.drop_table('playbooks')
    op.drop_index(op.f('ix_perps_tags_user_id'), table_name='perps_tags')
    op.drop_index(op.f('ix_perps_tags_id'), table_name='perps_tags')
    op.drop_table('perps_tags')
    op.drop_index(op.f('ix_perps_journal_user_id'), table_name='perps_journal')
    op.drop_index(op.f('ix_perps_journal_position_key'), table_name='perps_journal')
    op.drop_index(op.f('ix_perps_journal_id'), table_name='perps_journal')
    op.drop_table('perps_journal')
    op.drop_index(op.f('ix_exchange_accounts_user_id'), table_name='exchange_accounts')
    op.drop_index(op.f('ix_exchange_accounts_id'), table_name='exchange_accounts')
    op.drop_table('exchange_accounts')
    op.drop_index('ix_alerts_user_seen', table_name='alerts')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_alarms_user_status', table_name='alarms')
    op.drop_index(op.f('ix_alarms_user_id'), table_name='alarms')
    op.drop_index('ix_alarms_market_status', table_name='alarms')
    op.drop_index(op.f('ix_alarms_id'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('telegram_bot_config')
    # ### end Alembic commands ###
